name: Guns
version: 1.0
main: me.tomg.guns.Guns
description: Throw grenades in Minecraft!
author: Tom

commands:
    rod:
        usage: /<command>
        description: Get your magic wand!

permissions:
    guns.*:
        description: Use all guns commands.
        default: op
        children:
            guns.rod: true
    guns.rod:
        description: Get access to /rod
        default: true
